server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo1?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: true
    mode: HTML5
    servlet:
      content-type: text/html
    encoding: UTF-8
    suffix: .html
    check-template: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
  redis:
    port: 6379
    host: localhost
    database: 0
    password:
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      humio:
        tags:
          application: demo-springboot